env:
  global:
    secure: lh/DNYlFRpQZ8xPAYOld2tEmD0VdxNtINlTqKiUJl+5lLLb7IabfU10IVUK9FkKMhjGy1eUqV4dRdAk9ILk8+hKzi8WzhWVlyQ0SSaPKQtkP5zStoo2NQdtXopA1ikdoPG14IpPt2YkrIZ3U3xtALtJS1NlFA4HOpBarYkx9YrL7pO2NfeXouskjIXXCmJRtlU838e+k8XCkDPPtcmrj7wdTq99KZOP0dDIWvliXIe8ueG6MiZ3As7pM4iBhFgpnW5fNLgklk+VvzRg5TbCUZOSISrb1E1rwva4zeogeuhmOCfmvQmriSYFvl+uzhUgUbOIwoqjscNtNJh5WGgsu3wkfthrQi/ULioUi95wO1I3Sh7Zf+Un+zWyIHVD0xlvnhhKqnrncBy+gA1UJ2teRkHHIj4y6/8G+tFjLD1ihqYRqL9I27+kZPJRIfHlWP7DMuTGn52VYJ06AwLFiGQTZtn428/bGHd3znwVq/byLe6LnzAeU3/LdEqKyk2x/L1VtF6Ng+vHH5d6l3iswcghJQeaxRagXZMM+NoSLyHWWw+FXp0Y0X2uehubaHysNjugVUMWzSwQFK5sa2joblkanZ+pzqX2WLEn539bkyXr16W23OHm7ChkrdgzvSurWbXUEUzC7EdgQ+l9nOM11IIdhwXGSJ1rPLUhmPDEid7Tgn3I=
deploy:
  provider: script
  script: deploy/deploy.sh
  on:
    branch: master
